Update README
rojtekin/TDA-367-projektgrupp-14 pull request #63
Opened 2022-10-19 12:07 UTC by AbdullahDab01

2022-10-19 16:24 UTC, Suedie approved these changes
LGTM

2022-10-19 16:45 UTC, pkasinski requested changes

2022-10-19 16:45 UTC, pkasinski commented on README
> +## Creators
I think this is unnecessary. Instead I think a basic description of the project should be added.

2022-10-20 15:02 UTC, pkasinski approved these changes

2022-10-21 13:35 UTC, closed without merging